// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ocrosby/go-lab/lessons/07-interfaces-and-mocking (interfaces: TelemetryReporter)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_telemetry.go -package=mocks github.com/ocrosby/go-lab/lessons/07-interfaces-and-mocking TelemetryReporter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTelemetryReporter is a mock of TelemetryReporter interface.
type MockTelemetryReporter struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryReporterMockRecorder
	isgomock struct{}
}

// MockTelemetryReporterMockRecorder is the mock recorder for MockTelemetryReporter.
type MockTelemetryReporterMockRecorder struct {
	mock *MockTelemetryReporter
}

// NewMockTelemetryReporter creates a new mock instance.
func NewMockTelemetryReporter(ctrl *gomock.Controller) *MockTelemetryReporter {
	mock := &MockTelemetryReporter{ctrl: ctrl}
	mock.recorder = &MockTelemetryReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryReporter) EXPECT() *MockTelemetryReporterMockRecorder {
	return m.recorder
}

// ReportIgnition mocks base method.
func (m *MockTelemetryReporter) ReportIgnition(vin string, on bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportIgnition", vin, on)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportIgnition indicates an expected call of ReportIgnition.
func (mr *MockTelemetryReporterMockRecorder) ReportIgnition(vin, on any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportIgnition", reflect.TypeOf((*MockTelemetryReporter)(nil).ReportIgnition), vin, on)
}
