// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/health/health.go
//
// Generated by this command:
//
//	mockgen -source=pkg/health/health.go -destination=mocks/health_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	health "github.com/ocrosby/go-lab/projects/api/pkg/health"
)

// MockHealthChecker is a mock of HealthChecker interface.
type MockHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckerMockRecorder
	isgomock struct{}
}

// MockHealthCheckerMockRecorder is the mock recorder for MockHealthChecker.
type MockHealthCheckerMockRecorder struct {
	mock *MockHealthChecker
}

// NewMockHealthChecker creates a new mock instance.
func NewMockHealthChecker(ctrl *gomock.Controller) *MockHealthChecker {
	mock := &MockHealthChecker{ctrl: ctrl}
	mock.recorder = &MockHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthChecker) EXPECT() *MockHealthCheckerMockRecorder {
	return m.recorder
}

// AddCheck mocks base method.
func (m *MockHealthChecker) AddCheck(name string, check health.Check) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCheck", name, check)
}

// AddCheck indicates an expected call of AddCheck.
func (mr *MockHealthCheckerMockRecorder) AddCheck(name, check any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCheck", reflect.TypeOf((*MockHealthChecker)(nil).AddCheck), name, check)
}

// CheckHealth mocks base method.
func (m *MockHealthChecker) CheckHealth(ctx context.Context) *health.HealthStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(*health.HealthStatus)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockHealthCheckerMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockHealthChecker)(nil).CheckHealth), ctx)
}

// RemoveCheck mocks base method.
func (m *MockHealthChecker) RemoveCheck(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveCheck", name)
}

// RemoveCheck indicates an expected call of RemoveCheck.
func (mr *MockHealthCheckerMockRecorder) RemoveCheck(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCheck", reflect.TypeOf((*MockHealthChecker)(nil).RemoveCheck), name)
}
